cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'eza'
brew 'ffmpeg'
brew 'git'
brew 'helix'
brew 'htop'

brew 'node'
brew 'helix'
brew 'wget'
brew 'yt-dlp'

cask 'bitwarden'
cask 'android-platform-tools'
cask 'discord'
cask 'font-blex-mono-nerd-font'
cask 'ghostty'
cask 'messenger'
cask 'notion'
cask 'notion-calendar'
cask 'livebook'
cask 'popsql'
cask 'qbittorrent'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'syncplay'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'vlc'
# cask 'zen-browser'
cask 'zen-browser@twilight'
cask 'zoom'
