cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'eza'
brew 'helix'
brew 'wget'
brew 'yt-dlp'

cask 'bitwarden'
cask 'android-platform-tools'
cask 'messenger'
cask 'notion'
cask 'notion-calendar'
cask 'qbittorrent'
cask 'raycast'
cask 'whatsapp'
cask 'visual-studio-code'
cask 'vlc'
cask 'zoom'
