cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'eza'
brew 'ffmpeg'
brew 'git'
brew 'helix'
brew 'htop'
brew 'helix'
brew 'mise'
brew 'wget'
brew 'yt-dlp'

cask 'bitwarden'
cask 'android-platform-tools'
cask 'discord'
cask 'font-blex-mono-nerd-font'
cask 'ghostty'
brew 'postgresql@14'
cask 'messenger'
cask 'notion'
cask 'notion-calendar'
cask 'livebook'
cask 'popsql'
cask 'qbittorrent'
cask 'raycast'
cask 'slack'
cask 'spotify'
cask 'syncplay'
brew 'mise'
brew 'spotify'
brew 'helix'
brew 'starship'
brew 'git'

brew 'spaceman-diff'
brew 'wget'
brew 'yt-dlp'

cask 'android-platform-tools'
cask 'notion-calendar'
cask 'raycast'
cask 'whatsapp'
cask 'windsurf'
cask 'visual-studio-code'
cask 'vlc'
cask 'zen-browser@twilight'
cask 'zoom'
