####################
# Language Servers #
####################

[language-server.typescript]
command = "bunx" 
args = ["typescript-language-server", "--stdio"]
root_dir = "package.json"
config = {}

[language-server.javascript]
command = "vscode-langservers-extracted"
args = ["--stdio", "--language-servers=javascript"]
root_dir = "package.json"
config = {}

[language-server.clangd]
command = "clangd"
config = { clangd.fallbackFlags = [ "-std=gnu11" ] }
args = []

[language-server.ruff]
command = "ruff"
args = ["server"]

[language-server.ruff.config.settings]
logLevel = "debug"


##############
# Formatters #
##############

[formatter.prettier]
command = "prettier"
args = ["--stdin-filepath", "{file_path}"]



####################
# System Languages #
####################

# C
[[language]]
name = "c"
auto-format = false
language-servers = [ "clangd" ]

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
# comment-token = "//"
indent = { tab-width = 4, unit = "	"}
auto-format = true


#####################
# Backend Languages #
#####################

# Python
[[language]]
name = "python"
auto-format = true
# comment-token = "#"
file-types = ["py","pyi","py3","pyw",".pythonstartup",".pythonrc"]
indent = { tab-width = 4, unit = "    " }
injection-regex = "python"
language-servers = ["ruff"]
roots = [".", "pyproject.toml"]
shebangs = ["python"]

# Javascript

[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "tsx"
file-types = ["ts", "tsx"]
roots = ["package.json", "tsconfig.json"]
language-servers = ["typescript"]
auto-format = true
formatter = { name = "prettier", command = "bunx" , args = ["prettier", "--stdin-filepath", "{file_path}"] }

[[language]]
name = "javascript"
scope = "source.js"
injection-regex = "jsx"
file-types = ["js", "jsx", "cjs", "mjs"]
roots = ["package.json"]
language-servers = ["javascript"]
auto-format = true
formatter = { name = "prettier", command = "bunx prettier", args = ["--stdin-filepath", "{file_path}"] }


##############
# Web Design #
##############

[[language]]
name = "html"
formatter = { command = 'prettier', args = ["--parser", "html"] }

[[language]]
name = "json"
formatter = { command = 'prettier', args = ["--parser", "json"] }

[[language]]
name = "css"
formatter = { command = 'prettier', args = ["--parser", "css"] }

[[language]]
name = "tsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true

[[language]]
name = "jsx"
formatter = { command = 'prettier', args = ["--parser", "typescript"] }
auto-format = true


########
# Misc #
########

[[language]]
name = "markdown"
formatter = { command = 'prettier', args = ["--parser", "markdown"] }
auto-format = true

[[language]]
name = "hcl"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true

[[language]]
name = "tfvars"
formatter = { command = 'terraform', args = ["fmt", "-"] }
auto-format = true
